export default appStrings = Object.freeze({
  USERNAME: 'Username',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  REGISTER: 'Register',
  PRODUCTSLIST: 'ProductList',
  SEARCHSCREEN: 'SearchScreen',
  DASHBOARD: 'Dashboard',
  orLoginWith: 'or login with',
  firstName: 'First-Name',
  lastName: 'last-Name',
  maidenName: 'Maiden-Name',
  age: 'Age',
  gender: 'Gender',
  email: 'Email',
  phone: 'Phone',
  username: 'User-Name',
  password: 'Password',
  birthdate: 'Birth-Date',
  bloodGroup: 'Blood-Gr.',
  height: 'Height in CM',
  weight: 'Weight',
  hair: 'Hair',
  color: 'Color',
  type: 'Type',
  addres: 'Address',
  city: 'City',
  pinCode: 'PinCode',
  country: 'Country',
});
